name: sogra
description: "A new Flutter project."

publish_to: 'none'



environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^2.31.1
  firebase_auth: ^4.19.6
  cloud_firestore: ^4.17.4
  carousel_slider: ^4.2.1
  provider: ^6.1.2
  firebase_storage: ^11.7.6
  webview_flutter: ^2.0.13
  webview_flutter_android: ^3.16.2


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/logo.png
    - assets/map.png
    - assets/review.png
    - assets/image/
    - assets/kakao_map.html


  fonts:
    - family: GmarketSans
      fonts:
        - asset: assets/font/GmarketSans-Bold.ttf
        - asset: assets/font/GmarketSans-SemiBold.ttf
        - asset: assets/font/GmarketSans-Regular.ttf